begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,private,extensions;

select plan(31);

select ok(to_regclass('private.privacy_incident_register') is not null,'registre incidents confidentialité existe');
select ok(to_regclass('private.privacy_requests') is not null,'registre demandes vie privée existe');
select ok(to_regclass('private.privacy_legal_holds') is not null,'registre des obligations de conservation existe');
select ok(to_regclass('private.safety_escalation_cases') is not null,'dossiers escalade sécurité existent');
select ok((select relrowsecurity from pg_class where oid='private.privacy_incident_register'::regclass),'RLS incidents actif');
select ok((select relrowsecurity from pg_class where oid='private.privacy_requests'::regclass),'RLS demandes actif');
select ok((select relrowsecurity from pg_class where oid='private.privacy_legal_holds'::regclass),'RLS obligations de conservation actif');
select ok((select relrowsecurity from pg_class where oid='private.safety_escalation_cases'::regclass),'RLS escalades actif');
select ok(not has_table_privilege('anon','private.privacy_incident_register','select'),'anon ne lit pas les incidents');
select ok(not has_table_privilege('authenticated','private.privacy_incident_register','select'),'membre ne lit pas les incidents directement');
select ok(not has_table_privilege('anon','private.privacy_requests','select'),'anon ne lit pas les demandes');
select ok(not has_table_privilege('authenticated','private.privacy_requests','select'),'membre passe par RPC pour ses demandes');
select ok(to_regprocedure('public.privacy_create_request(text,text)') is not null,'RPC création demande existe');
select ok(to_regprocedure('public.privacy_my_requests(integer)') is not null,'RPC demandes personnelles existe');
select ok(to_regprocedure('public.privacy_admin_requests(integer)') is not null,'RPC admin demandes existe');
select ok(to_regprocedure('public.privacy_admin_record_incident(text,text,timestamptz,integer,text)') is not null,'RPC registre incident existe');
select ok(to_regprocedure('public.privacy_admin_incidents(integer)') is not null,'RPC consultation incidents existe');
select ok(to_regprocedure('public.safety_admin_escalation_cases(integer)') is not null,'RPC escalades sécurité existe');
select ok(has_function_privilege('authenticated','public.privacy_create_request(text,text)','execute'),'membre authentifié peut exercer ses droits');
select ok(not has_function_privilege('anon','public.privacy_create_request(text,text)','execute'),'anon ne crée pas une demande de compte');
select ok(has_function_privilege('authenticated','public.privacy_my_requests(integer)','execute'),'membre authentifié peut suivre ses demandes');
select ok(not has_function_privilege('anon','public.privacy_my_requests(integer)','execute'),'anon ne suit pas des demandes privées');
select ok(position('SINJIRA_MINIMUM_AGE_13' in pg_get_functiondef('public.handle_new_sinjira_user()'::regprocedure))>0,'inscription serveur minimum 13');
select ok(position('YOUTH_JURISDICTION_NOT_ENABLED' in pg_get_functiondef('public.handle_new_sinjira_user()'::regprocedure))>0,'comptes jeunesse hors juridiction validée bloqués côté serveur');
select ok(position('years<14' in replace(pg_get_functiondef('public.handle_new_sinjira_user()'::regprocedure),' ',''))>0,'autorisation parentale moins de 14 conservée');
select ok(position('SINJIRA_MINIMUM_AGE_13' in pg_get_functiondef('public.enforce_sinjira_account_safety_age()'::regprocedure))>0,'profil sécurité minimum 13');
select ok(position('5 years' in pg_get_functiondef('private.privacy_incident_retention_guard()'::regprocedure))>0,'rétention incidents cinq ans verrouillée');
select ok(position('30 days' in pg_get_functiondef('public.privacy_create_request(text,text)'::regprocedure))>0 or position('target_days' in pg_get_functiondef('public.privacy_create_request(text,text)'::regprocedure))>0,'demande informe cible 30 jours');
select ok(exists(select 1 from pg_trigger where tgrelid='public.social_reports'::regclass and tgname='trg_safety_create_escalation_case' and not tgisinternal),'escalade automatique signalements prioritaires active');
select is((select count(*)::int from pg_trigger where tgname='sinjira_content_policy_guard' and not tgisinternal),14,'les 14 gardes V24.4.82 restent actives');
select ok(exists(select 1 from pg_trigger where tgrelid='public.dating_profiles'::regclass and tgname='dating_profiles_adult_only' and not tgisinternal),'Rencontres 18+ reste verrouillé');
select * from finish();
rollback;