begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,private,extensions;

select plan(25);

select ok(to_regnamespace('sinjira_rls_internal') is not null,'schéma interne RLS existe');

select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'9 wrappers publics existent');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and not p.prosecdef and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'9 wrappers publics sont SECURITY INVOKER');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.provolatile='s' and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'9 wrappers publics restent STABLE');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('anon',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),0,'anon ne peut exécuter aucun wrapper');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('authenticated',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'authenticated conserve les 9 wrappers');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('service_role',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'service_role conserve les 9 wrappers');

select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='sinjira_rls_internal' and p.prosecdef and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'9 implémentations internes SECURITY DEFINER');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='sinjira_rls_internal' and p.provolatile='s' and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'9 implémentations internes restent STABLE');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='sinjira_rls_internal' and has_function_privilege('anon',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),0,'anon ne peut exécuter aucune implémentation interne');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='sinjira_rls_internal' and has_function_privilege('authenticated',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'authenticated garde EXECUTE interne nécessaire aux RLS');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='sinjira_rls_internal' and has_function_privilege('service_role',p.oid,'EXECUTE') and p.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'service_role garde EXECUTE interne');

select is((select count(*)::int from pg_proc p1 join pg_namespace n1 on n1.oid=p1.pronamespace join pg_proc p2 on p2.proname=p1.proname and pg_get_function_identity_arguments(p2.oid)=pg_get_function_identity_arguments(p1.oid) and pg_get_function_result(p2.oid)=pg_get_function_result(p1.oid) join pg_namespace n2 on n2.oid=p2.pronamespace where n1.nspname='public' and n2.nspname='sinjira_rls_internal' and p1.proname in ('is_fracture_party_member','moderation_content_visible','sinjira_can_social_interact','sinjira_content_allowed','sinjira_cycle_allowed','sinjira_mfa_access_allowed','sinjira_my_age_band','social_is_blocked','social_is_suspended')),9,'signatures publiques et internes identiques');

select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.is_fracture_party_member%'),4,'4 politiques utilisent is_fracture_party_member interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.moderation_content_visible%'),8,'8 politiques utilisent moderation_content_visible interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.sinjira_can_social_interact%'),19,'19 politiques utilisent sinjira_can_social_interact interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.sinjira_content_allowed%'),1,'1 politique utilise sinjira_content_allowed interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.sinjira_cycle_allowed%'),1,'1 politique utilise sinjira_cycle_allowed interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.sinjira_mfa_access_allowed%'),19,'19 politiques utilisent sinjira_mfa_access_allowed interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.sinjira_my_age_band%'),9,'9 politiques utilisent sinjira_my_age_band interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.social_is_blocked%'),8,'8 politiques utilisent social_is_blocked interne');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) like '%sinjira_rls_internal.social_is_suspended%'),12,'12 politiques utilisent social_is_suspended interne');

select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) ~ 'public\.(is_fracture_party_member|moderation_content_visible|sinjira_can_social_interact|sinjira_content_allowed|sinjira_cycle_allowed|sinjira_mfa_access_allowed|sinjira_my_age_band|social_is_blocked|social_is_suspended)'),0,'aucune politique ne pointe vers les nouveaux wrappers publics');
select is((select count(*)::int from pg_policies where lower(coalesce(qual,'')||' '||coalesce(with_check,'')) ~ 'sinjira_rls_internal\.(is_fracture_party_member|moderation_content_visible|sinjira_can_social_interact|sinjira_content_allowed|sinjira_cycle_allowed|sinjira_mfa_access_allowed|sinjira_my_age_band|social_is_blocked|social_is_suspended)'),81,'81 références RLS internes conservées');
select ok(has_schema_privilege('authenticated','sinjira_rls_internal','USAGE'),'authenticated possède USAGE nécessaire sur le schéma interne');

select * from finish();
rollback;
