project_id = "gpvivleexywljowcqkru"

[functions.send-game-report]
verify_jwt = false

[functions.get-document-url]
verify_jwt = false

[functions.submit-game-contribution]
verify_jwt = true

[functions.revoke-my-contributions]
verify_jwt = true

[functions.delete-player-account]
verify_jwt = true

[functions.admin-analytics]
verify_jwt = true

[functions.admin-console]
verify_jwt = true

[functions.send-player-sheet]
verify_jwt = true

[functions.submit-fracture-endgame]
verify_jwt = true

[functions.admin-reports]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.submit-character-questionnaire]
verify_jwt = true

[functions.admin-sinjira-v18]
verify_jwt = true

[functions.admin-social-v20]
verify_jwt = true
