import { createClient } from 'npm:@supabase/supabase-js@2';
import { PDFDocument, StandardFonts } from 'npm:pdf-lib@1.17.1';
const corsHeaders={'Access-Control-Allow-Origin':'https://www.benoitcantin.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}});
const PAID_EXTERNAL_SERVICES_ENABLED=false;
function service(){return createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}})}
async function userFrom(req:Request){const h=req.headers.get('Authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const {data,error}=await service().auth.getUser(token);return error?null:data.user}
function base64(bytes:Uint8Array){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({ok:false,error:'Méthode non autorisée.'},405);try{const user=await userFrom(req);if(!user?.email)return json({ok:false,error:'Connexion requise.'},401);if(!PAID_EXTERNAL_SERVICES_ENABLED)return json({ok:false,error:'Le transport courriel externe est préparé mais désactivé.',code:'PAID_EXTERNAL_SERVICE_DISABLED'},503);const body=await req.json();const mode=body?.mode==='solo'?'solo':'standard';const fields=body?.fields||{};const site='https://www.benoitcantin.com/projets/sinjira/jeux/fracture-du-reseau-mere/documents/';const template=mode==='solo'?`${site}SINJIRA_Mode_Solo_3_Joueurs_Interactive.pdf`:`${site}SINJIRA_Fiche_Joueur_1_Copie_Interactive.pdf`;const res=await fetch(template,{cache:'no-store'});if(!res.ok)return json({ok:false,error:'Le modèle PDF n’est pas encore disponible sur le site.'},503);const pdf=await PDFDocument.load(new Uint8Array(await res.arrayBuffer()));const form=pdf.getForm();for(const [name,value] of Object.entries(fields)){if(['session_title','party_code','player_label'].includes(name))continue;try{form.getTextField(name).setText(String(value??'').slice(0,6000))}catch{}}try{const font=await pdf.embedFont(StandardFonts.Helvetica);form.updateFieldAppearances(font)}catch{}const bytes=await pdf.save();const key=Deno.env.get('RESEND_API_KEY');if(!key)return json({ok:false,error:'Le service courriel SINJIRA n’est pas configuré.'},503);const from=Deno.env.get('REPORT_FROM_EMAIL')||'SINJIRA <no-reply@benoitcantin.com>';const filename=mode==='solo'?'SINJIRA_Fracture_Mode_Solo_3_Joueurs.pdf':'SINJIRA_Fracture_Fiche_Joueur.pdf';const sent=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[user.email],subject:mode==='solo'?'SINJIRA - Fiche privée mode solo':'SINJIRA - Fiche joueur privée',html:'<p>Voici votre fiche privée de <strong>SINJIRA - Fracture du Réseau-Mère</strong>.</p><p>Cette fiche n’est pas utilisée dans les données d’équilibrage du jeu.</p>',attachments:[{filename,content:base64(bytes)}]})});if(!sent.ok){console.error(await sent.text());return json({ok:false,error:'Le courriel n’a pas pu être envoyé.'},502)}return json({ok:true,email:user.email,mode});}catch(e){console.error(e);return json({ok:false,error:'Erreur lors de la préparation de la fiche.'},500)}});
