-- SINJIRA V20 — un personnage par compte + réseaux sociaux séparés + messageries séparées
create extension if not exists pgcrypto;

-- 1 compte = 1 demande de personnage = 1 personnage.
create or replace function public.enforce_one_character_submission_per_user() returns trigger language plpgsql security definer set search_path=public as $$
begin if exists(select 1 from public.character_submissions s where s.user_id=new.user_id and s.id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid)) then raise exception 'ONE_CHARACTER_SUBMISSION_PER_ACCOUNT'; end if; return new; end;$$;
drop trigger if exists one_character_submission_per_user on public.character_submissions;
create trigger one_character_submission_per_user before insert or update of user_id on public.character_submissions for each row execute function public.enforce_one_character_submission_per_user();
create or replace function public.enforce_one_character_per_user() returns trigger language plpgsql security definer set search_path=public as $$
begin if exists(select 1 from public.characters c where c.user_id=new.user_id and c.id<>coalesce(new.id,'00000000-0000-0000-0000-000000000000'::uuid)) then raise exception 'ONE_CHARACTER_PER_ACCOUNT'; end if; return new; end;$$;
drop trigger if exists one_character_per_user on public.characters;
create trigger one_character_per_user before insert or update of user_id on public.characters for each row execute function public.enforce_one_character_per_user();
alter table public.characters add column if not exists portrait_path text;

-- Profils sociaux publics sécurisés : aucune adresse courriel n'est exposée.
create table if not exists public.social_profiles(user_id uuid primary key references auth.users(id) on delete cascade,pseudo text not null default 'Membre SINJIRA',display_name text,avatar_path text,updated_at timestamptz not null default now());
create table if not exists public.character_social_profiles(character_id uuid primary key references public.characters(id) on delete cascade,user_id uuid not null unique references auth.users(id) on delete cascade,public_name text not null,public_description text,portrait_path text,status text not null,updated_at timestamptz not null default now());
create or replace function public.sync_social_profile_from_profile() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.social_profiles(user_id,pseudo,display_name,avatar_path,updated_at) values(new.user_id,coalesce(nullif(new.pseudo,''),'Membre SINJIRA'),new.display_name,new.avatar_path,now()) on conflict(user_id) do update set pseudo=excluded.pseudo,display_name=excluded.display_name,avatar_path=excluded.avatar_path,updated_at=now();return new;end;$$;
drop trigger if exists sync_social_profile_trigger on public.profiles;create trigger sync_social_profile_trigger after insert or update of pseudo,display_name,avatar_path on public.profiles for each row execute function public.sync_social_profile_from_profile();
insert into public.social_profiles(user_id,pseudo,display_name,avatar_path) select user_id,coalesce(nullif(pseudo,''),'Membre SINJIRA'),display_name,avatar_path from public.profiles on conflict(user_id) do update set pseudo=excluded.pseudo,display_name=excluded.display_name,avatar_path=excluded.avatar_path,updated_at=now();
create or replace function public.sync_character_social_profile() returns trigger language plpgsql security definer set search_path=public as $$begin if tg_op='DELETE' then delete from public.character_social_profiles where character_id=old.id;return old;end if;if new.visible_to_user=true and new.status in('approved','assigned','future','published') and nullif(new.public_name,'') is not null then insert into public.character_social_profiles(character_id,user_id,public_name,public_description,portrait_path,status,updated_at) values(new.id,new.user_id,new.public_name,new.public_description,new.portrait_path,new.status,now()) on conflict(character_id) do update set user_id=excluded.user_id,public_name=excluded.public_name,public_description=excluded.public_description,portrait_path=excluded.portrait_path,status=excluded.status,updated_at=now();else delete from public.character_social_profiles where character_id=new.id;end if;return new;end;$$;
drop trigger if exists sync_character_social_profile_trigger on public.characters;create trigger sync_character_social_profile_trigger after insert or update or delete on public.characters for each row execute function public.sync_character_social_profile();
insert into public.character_social_profiles(character_id,user_id,public_name,public_description,portrait_path,status) select id,user_id,public_name,public_description,portrait_path,status from public.characters where visible_to_user=true and status in('approved','assigned','future','published') and nullif(public_name,'') is not null on conflict(character_id) do update set user_id=excluded.user_id,public_name=excluded.public_name,public_description=excluded.public_description,portrait_path=excluded.portrait_path,status=excluded.status,updated_at=now();

-- Règles et blocages.
create table if not exists public.community_rule_acceptances(user_id uuid not null references auth.users(id) on delete cascade,rules_version text not null,accepted_at timestamptz not null default now(),primary key(user_id,rules_version));
create table if not exists public.social_blocks(blocker_user_id uuid not null references auth.users(id) on delete cascade,blocked_user_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),primary key(blocker_user_id,blocked_user_id),check(blocker_user_id<>blocked_user_id));
create table if not exists public.social_suspensions(user_id uuid primary key references auth.users(id) on delete cascade,reason text,until_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create or replace function public.has_accepted_community_rules(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.community_rule_acceptances a where a.user_id=p_user_id and a.rules_version='sinjira-community-rules-v1-2026-08-12');$$;
create or replace function public.social_is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.social_blocks x where (x.blocker_user_id=a and x.blocked_user_id=b) or (x.blocker_user_id=b and x.blocked_user_id=a));$$;
create or replace function public.social_is_suspended(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.social_suspensions s where s.user_id=p_user_id and (s.until_at is null or s.until_at>now()));$$;

-- Réseau compte réel.
create table if not exists public.social_real_posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,body text not null check(char_length(body) between 1 and 3000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.social_real_comments(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.social_real_posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,body text not null check(char_length(body) between 1 and 1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.social_real_likes(post_id uuid not null references public.social_real_posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),primary key(post_id,user_id));
create table if not exists public.social_real_messages(id uuid primary key default gen_random_uuid(),sender_user_id uuid not null references auth.users(id) on delete cascade,recipient_user_id uuid not null references auth.users(id) on delete cascade,body text not null check(char_length(body) between 1 and 4000),created_at timestamptz not null default now(),read_at timestamptz,check(sender_user_id<>recipient_user_id));

-- Réseau personnage totalement distinct.
create table if not exists public.social_character_posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,character_id uuid not null references public.character_social_profiles(character_id) on delete cascade,body text not null check(char_length(body) between 1 and 3000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.social_character_comments(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.social_character_posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,character_id uuid not null references public.character_social_profiles(character_id) on delete cascade,body text not null check(char_length(body) between 1 and 1000),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.social_character_likes(post_id uuid not null references public.social_character_posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,character_id uuid not null references public.character_social_profiles(character_id) on delete cascade,created_at timestamptz not null default now(),primary key(post_id,user_id));
create table if not exists public.social_character_messages(id uuid primary key default gen_random_uuid(),sender_user_id uuid not null references auth.users(id) on delete cascade,recipient_user_id uuid not null references auth.users(id) on delete cascade,sender_character_id uuid not null references public.character_social_profiles(character_id) on delete cascade,recipient_character_id uuid not null references public.character_social_profiles(character_id) on delete cascade,body text not null check(char_length(body) between 1 and 4000),created_at timestamptz not null default now(),read_at timestamptz,check(sender_user_id<>recipient_user_id));

-- Signalements. Pour un message privé, snapshot contient uniquement le message explicitement signalé.
create table if not exists public.social_reports(id uuid primary key default gen_random_uuid(),reporter_user_id uuid not null references auth.users(id) on delete cascade,network text not null check(network in('real','character')),target_type text not null check(target_type in('post','comment','message','profile')),target_id uuid not null,reason text not null,snapshot jsonb not null default '{}'::jsonb,status text not null default 'open' check(status in('open','resolved','dismissed')),created_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete set null);

-- Future boutique : structure prête sans paiement actif.
create table if not exists public.products(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,product_type text not null default 'digital',active boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,order_number text not null unique,status text not null default 'pending',currency text not null default 'CAD',total_cents integer not null default 0,provider text,provider_reference text,created_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,quantity integer not null default 1,unit_price_cents integer not null default 0);
create table if not exists public.user_entitlements(user_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,source text not null default 'purchase',granted_at timestamptz not null default now(),primary key(user_id,product_id));

-- updated_at
drop trigger if exists social_real_posts_updated_at on public.social_real_posts;create trigger social_real_posts_updated_at before update on public.social_real_posts for each row execute function public.set_updated_at();
drop trigger if exists social_real_comments_updated_at on public.social_real_comments;create trigger social_real_comments_updated_at before update on public.social_real_comments for each row execute function public.set_updated_at();
drop trigger if exists social_character_posts_updated_at on public.social_character_posts;create trigger social_character_posts_updated_at before update on public.social_character_posts for each row execute function public.set_updated_at();
drop trigger if exists social_character_comments_updated_at on public.social_character_comments;create trigger social_character_comments_updated_at before update on public.social_character_comments for each row execute function public.set_updated_at();

-- RLS
alter table public.social_profiles enable row level security;alter table public.character_social_profiles enable row level security;alter table public.community_rule_acceptances enable row level security;alter table public.social_blocks enable row level security;alter table public.social_suspensions enable row level security;alter table public.social_real_posts enable row level security;alter table public.social_real_comments enable row level security;alter table public.social_real_likes enable row level security;alter table public.social_real_messages enable row level security;alter table public.social_character_posts enable row level security;alter table public.social_character_comments enable row level security;alter table public.social_character_likes enable row level security;alter table public.social_character_messages enable row level security;alter table public.social_reports enable row level security;alter table public.products enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.user_entitlements enable row level security;

-- Profils publics sûrs.
drop policy if exists social_profiles_read on public.social_profiles;create policy social_profiles_read on public.social_profiles for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
drop policy if exists character_social_profiles_read on public.character_social_profiles;create policy character_social_profiles_read on public.character_social_profiles for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
-- Acceptation des règles.
drop policy if exists community_rules_own on public.community_rule_acceptances;create policy community_rules_own on public.community_rule_acceptances for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
-- Blocages.
drop policy if exists social_blocks_own on public.social_blocks;create policy social_blocks_own on public.social_blocks for all to authenticated using(auth.uid()=blocker_user_id) with check(auth.uid()=blocker_user_id);
-- Suspensions privées : pas de politique utilisateur.
revoke all on public.social_suspensions from anon,authenticated;

-- Réseau réel.
drop policy if exists real_posts_read on public.social_real_posts;create policy real_posts_read on public.social_real_posts for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
drop policy if exists real_posts_insert on public.social_real_posts;create policy real_posts_insert on public.social_real_posts for insert to authenticated with check(auth.uid()=user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()));
drop policy if exists real_posts_update on public.social_real_posts;create policy real_posts_update on public.social_real_posts for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists real_posts_delete on public.social_real_posts;create policy real_posts_delete on public.social_real_posts for delete to authenticated using(auth.uid()=user_id);
drop policy if exists real_comments_read on public.social_real_comments;create policy real_comments_read on public.social_real_comments for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
drop policy if exists real_comments_insert on public.social_real_comments;create policy real_comments_insert on public.social_real_comments for insert to authenticated with check(auth.uid()=user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()));
drop policy if exists real_comments_change on public.social_real_comments;create policy real_comments_change on public.social_real_comments for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists real_likes_read on public.social_real_likes;create policy real_likes_read on public.social_real_likes for select to authenticated using(true);
drop policy if exists real_likes_own on public.social_real_likes;create policy real_likes_own on public.social_real_likes for insert to authenticated with check(auth.uid()=user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()));drop policy if exists real_likes_delete on public.social_real_likes;create policy real_likes_delete on public.social_real_likes for delete to authenticated using(auth.uid()=user_id);
drop policy if exists real_messages_read on public.social_real_messages;create policy real_messages_read on public.social_real_messages for select to authenticated using(auth.uid() in(sender_user_id,recipient_user_id));
drop policy if exists real_messages_insert on public.social_real_messages;create policy real_messages_insert on public.social_real_messages for insert to authenticated with check(auth.uid()=sender_user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()) and not public.social_is_blocked(sender_user_id,recipient_user_id));

-- Réseau personnage.
drop policy if exists char_posts_read on public.social_character_posts;create policy char_posts_read on public.social_character_posts for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
drop policy if exists char_posts_insert on public.social_character_posts;create policy char_posts_insert on public.social_character_posts for insert to authenticated with check(auth.uid()=user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()) and exists(select 1 from public.character_social_profiles c where c.character_id=character_id and c.user_id=auth.uid()));
drop policy if exists char_posts_update on public.social_character_posts;create policy char_posts_update on public.social_character_posts for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists char_posts_delete on public.social_character_posts;create policy char_posts_delete on public.social_character_posts for delete to authenticated using(auth.uid()=user_id);
drop policy if exists char_comments_read on public.social_character_comments;create policy char_comments_read on public.social_character_comments for select to authenticated using(not public.social_is_blocked(auth.uid(),user_id));
drop policy if exists char_comments_insert on public.social_character_comments;create policy char_comments_insert on public.social_character_comments for insert to authenticated with check(auth.uid()=user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()) and exists(select 1 from public.character_social_profiles c where c.character_id=character_id and c.user_id=auth.uid()));
drop policy if exists char_comments_change on public.social_character_comments;create policy char_comments_change on public.social_character_comments for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists char_likes_read on public.social_character_likes;create policy char_likes_read on public.social_character_likes for select to authenticated using(true);
drop policy if exists char_likes_insert on public.social_character_likes;create policy char_likes_insert on public.social_character_likes for insert to authenticated with check(auth.uid()=user_id and exists(select 1 from public.character_social_profiles c where c.character_id=character_id and c.user_id=auth.uid()));drop policy if exists char_likes_delete on public.social_character_likes;create policy char_likes_delete on public.social_character_likes for delete to authenticated using(auth.uid()=user_id);
drop policy if exists char_messages_read on public.social_character_messages;create policy char_messages_read on public.social_character_messages for select to authenticated using(auth.uid() in(sender_user_id,recipient_user_id));
drop policy if exists char_messages_insert on public.social_character_messages;create policy char_messages_insert on public.social_character_messages for insert to authenticated with check(auth.uid()=sender_user_id and public.has_accepted_community_rules(auth.uid()) and not public.social_is_suspended(auth.uid()) and not public.social_is_blocked(sender_user_id,recipient_user_id) and exists(select 1 from public.character_social_profiles c where c.character_id=sender_character_id and c.user_id=auth.uid()) and exists(select 1 from public.character_social_profiles c where c.character_id=recipient_character_id and c.user_id=recipient_user_id));

-- Signalements utilisateur.
drop policy if exists social_reports_own_insert on public.social_reports;create policy social_reports_own_insert on public.social_reports for insert to authenticated with check(auth.uid()=reporter_user_id and public.has_accepted_community_rules(auth.uid()));drop policy if exists social_reports_own_read on public.social_reports;create policy social_reports_own_read on public.social_reports for select to authenticated using(auth.uid()=reporter_user_id);

-- Achats : lecture privée seulement; aucune écriture client.
drop policy if exists products_active_read on public.products;create policy products_active_read on public.products for select to authenticated using(active=true);
drop policy if exists orders_own_read on public.orders;create policy orders_own_read on public.orders for select to authenticated using(auth.uid()=user_id);
drop policy if exists order_items_own_read on public.order_items;create policy order_items_own_read on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists entitlements_own_read on public.user_entitlements;create policy entitlements_own_read on public.user_entitlements for select to authenticated using(auth.uid()=user_id);

-- Fonctions auxiliaires non modifiables par les comptes.
revoke all on function public.has_accepted_community_rules(uuid) from public;grant execute on function public.has_accepted_community_rules(uuid) to authenticated,service_role;
revoke all on function public.social_is_blocked(uuid,uuid) from public;grant execute on function public.social_is_blocked(uuid,uuid) to authenticated,service_role;
revoke all on function public.social_is_suspended(uuid) from public;grant execute on function public.social_is_suspended(uuid) to authenticated,service_role;

create index if not exists social_real_posts_created_idx on public.social_real_posts(created_at desc);create index if not exists social_real_comments_post_idx on public.social_real_comments(post_id,created_at);create index if not exists social_real_messages_pair_idx on public.social_real_messages(sender_user_id,recipient_user_id,created_at);create index if not exists social_character_posts_created_idx on public.social_character_posts(created_at desc);create index if not exists social_character_comments_post_idx on public.social_character_comments(post_id,created_at);create index if not exists social_character_messages_pair_idx on public.social_character_messages(sender_character_id,recipient_character_id,created_at);create index if not exists social_reports_status_idx on public.social_reports(status,created_at desc);
